DROP TABLE IF EXISTS SHOW;

CREATE TABLE SHOW
(
    SHOW_NUMBER VARCHAR(20) PRIMARY KEY,
    NUM_OF_ROWS INTEGER NOT NULL,
    SEATS_PER_ROW INTEGER NOT NULL,
    CANCELLATION_WINDOW_MINS INTEGER NOT NULL,
    AVAILABLE_SEATS VARCHAR(780)
);

DROP TABLE IF EXISTS BOOKING;

CREATE TABLE BOOKING
(
    TICKET_ID VARCHAR(40) PRIMARY KEY,
    PHONE INTEGER NOT NULL,
    SHOW_NO VARCHAR(20) NOT NULL,
    BOOKED_SEATS VARCHAR(780) NOT NULL,
    BOOKING_TIME TIMESTAMP NOT NULL
);