DROP TABLE IF EXISTS SHOW;

CREATE TABLE SHOW
(
    ID INTEGER PRIMARY KEY,
    SHOW_NO INTEGER NOT NULL,  
    NUM_OF_ROWS INTEGER NOT NULL,
    SEATS_PER_ROW INTEGER NOT NULL,
    CANCELLATION_WINDOW_MINS INTEGER NOT NULL
);
