DROP TABLE IF EXISTS SHOW;

CREATE TABLE SHOW
(
    SHOW_NUMBER VARCHAR(20) PRIMARY KEY,
    NUM_OF_ROWS INTEGER NOT NULL,
    SEATS_PER_ROW INTEGER NOT NULL,
    CANCELLATION_WINDOW_MINS INTEGER NOT NULL,
    AVAILABLE_SEATS VARCHAR(780)
);

DROP TABLE IF EXISTS BOOKING;

CREATE TABLE BOOKING
(
    PHONE INTEGER PRIMARY KEY,
    SHOW_NO INTEGER NOT NULL,
    BOOKED_SEATS VARCHAR(780) NOT NULL
);